version: "3.9"
services:
  app:
    # platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
        NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: ${NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}
        NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: ${NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}
        NEXT_PUBLIC_S3_ACCESS_KEY_ID: ${NEXT_PUBLIC_S3_ACCESS_KEY_ID}
        NEXT_PUBLIC_S3_SECRET_ACCESS_KEY: ${NEXT_PUBLIC_S3_SECRET_ACCESS_KEY}
        NEXT_PUBLIC_S3_BUCKET_NAME: ${NEXT_PUBLIC_S3_BUCKET_NAME}
        NEXT_PUBLIC_S3_REGION: ${NEXT_PUBLIC_S3_REGION}
        PINECONE_API_KEY: ${PINECONE_API_KEY}
        OPENAI_API_SECRET_KEY: ${OPENAI_API_SECRET_KEY}
        LLAMA_API_URL: ${LLAMA_API_URL}
        EMBEDDING_API_URL: ${EMBEDDING_API_URL}

    working_dir: /app

    ports:
      - "3000:3000"
    image: paperhub-nextjs
    env_file:
      - .env
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge